name: Build Vue WebApp

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '21.x'
      uses: actions/setup-node@v2
      with:
        node-version: "21.x"
        cache: "npm"

    - id: Build-Vue
      uses: SerhiiKa/VuePagesAction@1.0.4
      with:
        username: 'xarantolus'
        reponame: 'postbank-konto-chart'
        token: ${{ secrets.GITHUB_TOKEN }}
