name: Build Vue WebApp

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2

    - name: Vue App to Github Pages
      uses: StruggleYang/VuePagesAction@2.0.0
      with:
        useyarn: false
